// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperFilm.Enerji.Entites;

#nullable disable

namespace SuperFilm.Enerji.Entites.Migrations
{
    [DbContext(typeof(EnerjiDbContext))]
    [Migration("20250620064652_EnerjiRequest_add")]
    partial class EnerjiRequest_add
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SuperFilm.Enerji.Entites.EnerjiRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("smalldatetime");

                    b.HasKey("Id");

                    b.ToTable("EnerjiRequest");
                });

            modelBuilder.Entity("SuperFilm.Enerji.Entites.EnerjiRequestAdvance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EndDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EnerjiRequestId")
                        .HasColumnType("int");

                    b.Property<string>("ProductionLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartTime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EnerjiRequestId");

                    b.ToTable("EnerjiRequestAdvance");
                });

            modelBuilder.Entity("SuperFilm.Enerji.Entites.IsYeri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Adi")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Kodu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("ISYERI");
                });

            modelBuilder.Entity("SuperFilm.Enerji.Entites.Isletme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("IsyeriId")
                        .HasColumnType("int");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Tip")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IsyeriId");

                    b.ToTable("ISLETME");
                });

            modelBuilder.Entity("SuperFilm.Enerji.Entites.IsletmeSayacDagilimi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Carpan")
                        .HasColumnType("decimal(7,6)");

                    b.Property<string>("Islem")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("int");

                    b.Property<int>("SayacId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsletmeId");

                    b.HasIndex("SayacId");

                    b.ToTable("ISLETME_SAYAC_DAGILIMI");
                });

            modelBuilder.Entity("SuperFilm.Enerji.Entites.OpcNodes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttributeId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("NodeNameSpace")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OPC_NODES");
                });

            modelBuilder.Entity("SuperFilm.Enerji.Entites.OpcNodesIsletmeDagilimi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Carpan")
                        .HasColumnType("decimal(7,6)");

                    b.Property<string>("Islem")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("int");

                    b.Property<int>("OpcNodesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsletmeId");

                    b.HasIndex("OpcNodesId");

                    b.ToTable("OPC_NODES_ISLETME_DAGILIMI");
                });

            modelBuilder.Entity("SuperFilm.Enerji.Entites.SayacTanimlari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int");

                    b.Property<string>("SayacAciklama")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SayacKodu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SayacTanimi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SayacYeri")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("SAYAC_TANIMLARI");
                });

            modelBuilder.Entity("SuperFilm.Enerji.Entites.SayacVeri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ay")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Deger")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Gun")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Kod")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("NormalizeDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OpcNodesId")
                        .HasColumnType("int");

                    b.Property<int?>("SayacId")
                        .HasColumnType("int");

                    b.Property<string>("Yil")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("Zaman")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.HasKey("Id");

                    b.ToTable("SAYAC_VERI");
                });

            modelBuilder.Entity("SuperFilm.Enerji.Entites.EnerjiRequestAdvance", b =>
                {
                    b.HasOne("SuperFilm.Enerji.Entites.EnerjiRequest", null)
                        .WithMany("EnerjiRequestAdvanceBody")
                        .HasForeignKey("EnerjiRequestId");
                });

            modelBuilder.Entity("SuperFilm.Enerji.Entites.Isletme", b =>
                {
                    b.HasOne("SuperFilm.Enerji.Entites.IsYeri", "Isyeri")
                        .WithMany("Isletmeler")
                        .HasForeignKey("IsyeriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Isyeri");
                });

            modelBuilder.Entity("SuperFilm.Enerji.Entites.IsletmeSayacDagilimi", b =>
                {
                    b.HasOne("SuperFilm.Enerji.Entites.Isletme", "Isletme")
                        .WithMany()
                        .HasForeignKey("IsletmeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SuperFilm.Enerji.Entites.SayacTanimlari", "Sayac")
                        .WithMany()
                        .HasForeignKey("SayacId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Isletme");

                    b.Navigation("Sayac");
                });

            modelBuilder.Entity("SuperFilm.Enerji.Entites.OpcNodesIsletmeDagilimi", b =>
                {
                    b.HasOne("SuperFilm.Enerji.Entites.Isletme", "Isletme")
                        .WithMany()
                        .HasForeignKey("IsletmeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SuperFilm.Enerji.Entites.OpcNodes", "OpcNodes")
                        .WithMany()
                        .HasForeignKey("OpcNodesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Isletme");

                    b.Navigation("OpcNodes");
                });

            modelBuilder.Entity("SuperFilm.Enerji.Entites.EnerjiRequest", b =>
                {
                    b.Navigation("EnerjiRequestAdvanceBody");
                });

            modelBuilder.Entity("SuperFilm.Enerji.Entites.IsYeri", b =>
                {
                    b.Navigation("Isletmeler");
                });
#pragma warning restore 612, 618
        }
    }
}
